name: Actualizar Cotizaciones

on:
  schedule:
    - cron: '0 * * * 1-5'
  workflow_dispatch:

# Definimos la variable a nivel global del flujo para mutar el comportamiento de todas las acciones
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar el Scraping
        run: node scraper.js

      - name: Guardar cambios y subirlos a GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          git add cotizaciones.json
          git commit -m "Bot: Cotizaciones actualizadas automáticamente" || exit 0
          git push
